name: "Builder"
on: [ push, pull_request ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Fix Gradle Permissions
        run: chmod +x gradlew
      - name: Execute Gradle build
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: build_output
          path: build/libs/*
